kubectl delete namespace/ingress-nginx 
kubectl delete serviceaccount/ingress-nginx 
kubectl delete configmap/ingress-nginx-controller 
kubectl delete clusterrole.rbac.authorization.k8s.io/ingress-nginx 
kubectl delete clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx 
kubectl delete role.rbac.authorization.k8s.io/ingress-nginx 
kubectl delete rolebinding.rbac.authorization.k8s.io/ingress-nginx 
kubectl delete service/ingress-nginx-controller-admission 
kubectl delete service/ingress-nginx-controller 
kubectl delete deployment.apps/ingress-nginx-controller 
kubectl delete validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission 
kubectl delete serviceaccount/ingress-nginx-admission 
kubectl delete clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission 
kubectl delete clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission 
kubectl delete role.rbac.authorization.k8s.io/ingress-nginx-admission 
kubectl delete rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission 
kubectl delete job.batch/ingress-nginx-admission-create 
kubectl delete job.batch/ingress-nginx-admission-patch 
