apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-08ca6b30177f6ca4a 
    fsType: gp2
  hostPath:
    path: "/Users/williamcrupi/Documents/kube/aws/data"
